### PR TITLE
Line length check functionality

### PR DESCRIPTION
**Pull request by vahe-evoyan**
Adds another option to check the length of lines in the code.

P.S. Not sure if this fits into the project scope, but I found very easy to integrate my code check idea with your code structure.

### CODE REVIEW

**Comment by schorfES** [comment]
Hi and first of all, thank you for contributing to this project. I've discussed this feature with all my colleagues, but the leading opinion was that this won't fit into the project scope.

Sorry for dropping your effort, but we got an idea: What do you think about an plugin mechanism, where everybody can add his own functionality (which may not really match into the project scope)?

**Comment by vahe-evoyan** [comment]
That's a great idea. Let me know if I can help you with implementation.

**Comment by evanshortiss** [comment]
Hi @vahe-evoyan I wrote a module to check line length that I frequently use in conjunction with lintspaces. This is it here: https://www.npmjs.com/package/linelint

**Comment by vahe-evoyan** [comment]
Thanks @evanshortiss! Nice tool!

**Pull request closed without merging**
