### PR TITLE
Add support for end-of-line validation

### PR DESCRIPTION
**Pull request by crabbkw**

### CODE REVIEW

**Comment by schorfES** [comment]
Hi @crabbkw,

I really like this PR and would like to merge and release it as soon as possible. I've found 2 small things you may can do to finalize the PR:

* The name of the option `end_of_line` matches the editor-config name, but it would be nice if the lintspaces option is written in camelcase like `endOfLine`. This matches the style of the other options like `indentationGuess ` and `allowsBOM`.
* The documentation you've added to the README.md will be dropped by the build process (`grunt docs `). Please update the [docs/options.md](https://github.com/schorfES/node-lintspaces/blob/master/docs/options.md) instead.

I thank you very much for supporting this project! ❤️

**Comment by crabbkw** [comment]
I will make the suggested changes and push a new commit to the branch. Thanks for taking the time to review!

**Comment by crabbkw** [comment]
If this gets accepted, I would appreciate getting another release of grunt-lintspaces that uses the updated node-lintspaces library.

Thanks again for taking the time to look at the PR!

**Comment by schorfES** [comment]
Yes, for shure! I will release for both packages a new version when this PR is accepted. Thanks in advance for adding the mentioned changes. I'm looking forward to click the "merge" button...

**Comment by crabbkw** [comment]
I have made the requested changes. Can you please take another look?

**Comment by schorfES** [comment]
I've released the a new version of lintspaces@0.5.0 and a new version of grunt-lintspaces@0.8.0 on npm. Thank you for your support!!!

**Pull request merged**
